---
abstract: 'report on and update an SQLite database.'
author:
  - 'Kathryn Andersen'
build_requires:
  File::Find: 0
  Module::Build: 0.3601
  Test::Distribution: 0
  Test::More: 0
  perl: 5.8.5
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQLite-Work
requires:
  CGI: 0
  DBI: 0
  Data::Dumper: 0
  File::Temp: 0
  Getopt::ArgvFile: 0
  Getopt::Long: 2.34
  POSIX: 0
  Pod::Usage: 0
  Text::NeatTemplate: 0
version: 0.1003
